version: '3'

services:
  appbackoffice: 
    container_name: appbackoffice
    build: .
    ports:
      - 8080:1337
    restart: always
    link:
      - db
    env_file: .env


  db:
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: .env
    volumes:
    - $MARIADB_PATH:/var/lib/mysql
      


  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    link:
      - db